"use client";
import { useEffect, useState } from "react";
import { scenes, statLabels } from "../data/story";
import { advance, isGame, newGame, resolveEnding, selectChoice, STORAGE_KEY } from "../lib/engine";
import type { Game, Stat } from "../types";
function Icon({ name, size = 18 }: { name: string; size?: number }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name === "arrow" ? <path d="M4 12h16m-6-6 6 6-6 6"/> : name === "settings" ? <><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/></> : name === "close" ? <path d="m6 6 12 12M18 6 6 18"/> : name === "check" ? <path d="m5 12 4 4L19 6"/> : name === "chat" ? <><path d="M20 4H4v13h4l4 4v-4h8Z"/><path d="M8 8h8M8 12h5"/></> : <path d="m12 2 2.6 7.4L22 12l-7.4 2.6L12 22l-2.6-7.4L2 12l7.4-2.6Z"/>}</svg>;
}
export default function StoryGame({ initialReader = false }: { initialReader?: boolean }) {
  const [playing, setPlaying] = useState(initialReader);
  const [game, setGame] = useState<Game>(() => newGame());
  const [hasSave, setHasSave] = useState(false);
  const [modal, setModal] = useState<"fate" | "settings" | null>(null);
  const [bullets, setBullets] = useState(true);
  const [fontSize, setFontSize] = useState(18);
  const [saveOk, setSaveOk] = useState(true);
  const [ready, setReady] = useState(false);
  const [restartOpen, setRestartOpen] = useState(false);
  useEffect(() => {
    const frame = requestAnimationFrame(() => {
      try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const g: unknown = JSON.parse(raw); if (isGame(g)) { setGame(g); setHasSave(true); } }
        const prefs = JSON.parse(localStorage.getItem("fudimo-preferences") || "null");
        if (prefs && typeof prefs.bullets === "boolean" && [16,18,20,22,24].includes(prefs.fontSize)) { setBullets(prefs.bullets); setFontSize(prefs.fontSize); }
      } catch { /* Invalid saves and unavailable storage start safely. */ }
      setReady(true);
    }); return () => cancelAnimationFrame(frame);
  }, []);
  useEffect(() => { if (ready) { try { localStorage.setItem("fudimo-preferences", JSON.stringify({bullets,fontSize})); } catch { /* Preferences remain available for this session. */ } } }, [ready,bullets,fontSize]);
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); }, [playing]);
  useEffect(() => { if (!modal && !restartOpen) return; const close = (e: KeyboardEvent) => { if (e.key === "Escape") { setModal(null); setRestartOpen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [modal,restartOpen]);
  const persist = (g: Game) => { setGame(g); try { localStorage.setItem(STORAGE_KEY, JSON.stringify(g)); setHasSave(true); setSaveOk(true); } catch { setSaveOk(false); } };
  const start = () => { persist(newGame(game.endings)); setPlaying(true); setRestartOpen(false); setModal(null); };
  const requestStart = () => { if (hasSave && !scenes[game.scene].finale) setRestartOpen(true); else start(); };
  const beat = scenes[game.scene];
  const choice = beat.choices?.find(c=>c.id===game.choices[beat.id]);
  const text = game.phase === "reply" ? choice?.reply : game.phase === "response" ? choice?.response : beat.text;
  const effect = game.phase === "reply" ? choice : null;
  const speaker = game.phase === "intro" ? beat.speaker : game.phase === "reply" ? "我" : "旁白";
  const stats = Object.entries(game.stats).map(([stat,value])=>[statLabels[stat as Stat],value] as const);
  const ending = resolveEnding(game);
  return <div className="demo-shell"><header className="topbar"><button className="brand" onClick={() => setPlaying(false)} aria-label="返回首页"><span className="brand-symbol">扶</span><span>扶弟魔模拟器<small>REWRITE YOUR DESTINY</small></span></button><nav><button onClick={() => setModal("fate")}><Icon name="spark"/>命运面板</button><button onClick={() => setModal("settings")} aria-label="设置"><Icon name="settings"/><span>设置</span></button></nav><span className="edition"><i/> 人生由我决定 <b>01</b></span></header>
    <main className={playing ? "reader-layout" : "home-layout"}>{!playing ? <>
      <section className="hero"><div className="eyebrow"><span/> 互动剧情游戏 <b>/</b> 女性成长 · 反套路</div><h1>扶弟魔<br/><span>模拟器</span></h1><p className="hero-quote">他们让我让着弟弟。<br/>他却让我，<span>别让。</span></p><p className="hero-description">我本该是恶毒女配，但我偏要亲手改写剧本。<br/>读书、逃离、成长。这一次，人生由我决定。</p><div className="hero-actions"><button className="primary" disabled={!ready} onClick={requestStart}>开始改写命运 <Icon name="arrow" size={21}/></button><button className="continue" disabled={!ready || !hasSave} onClick={() => setPlaying(true)}>{hasSave ? "继续上次游戏" : "你的故事，尚未开始"}<span>↗</span></button></div><div className="hero-note"><Icon name="check" size={14}/> 进度自动保存于本机 <span>·</span> 每个选择，都有回响</div><div className="themes"><span>01 <b>姐弟羁绊</b></span><span>02 <b>打破设定</b></span><span>03 <b>自我成长</b></span></div></section>
      <section className="preview-stage" aria-label="剧情预览"><div className="stage-orbit"/><span className="stage-coordinate">FATE REWRITING / 001</span><div className="floating-note"><i/> 原定命运 <span>恶毒女配</span><Icon name="arrow" size={14}/><b>由你定义</b></div><article className="preview-card"><div className="card-top"><span><i/> 故事的起点</span><span>THE FIRST CHOICE</span></div><div className="preview-location">家里的饭桌 <span>/</span> 夏末 · 傍晚</div><h2>他们说，<br/>女孩子读那么多书没用。</h2><div className="preview-narrative"><p>饭桌上，父亲把两张报名表推到一边。</p><p>“家里只能供一个。你是姐姐，<br/>就让让你弟弟吧。”</p><p>我低着头，手里的筷子迟迟没有落下。</p></div><div className="character-line"><span className="character-mark">嘉</span><div><small>嘉豪 <span>你的弟弟</span></small><p>“谁说我要读了？老子不读。”</p></div><span className="tiny-spark">✳</span></div><button className="preview-choice" onClick={requestStart}><Icon name="spark" size={16}/><span>这一次，你会怎么选？</span><Icon name="arrow" size={17}/></button><div className="card-bottom"><span>你的故事，尚未被定义。</span><span>START / ↗</span></div></article><div className="bullet-float"><Icon name="chat" size={16}/><span>等一下，这黄毛好像在保护姐姐？</span><small>弹幕</small></div><span className="stage-caption">THE STORY IS YOURS TO CHANGE.</span></section>
    </> : <><aside className="reader-aside"><button className="back-link" onClick={() => setPlaying(false)}>← 返回首页</button><div className="eyebrow">YOUR STORY</div><h2>{beat.aside.split("|").map((line,i)=><span className="aside-title-line" key={i}>{line}</span>)}</h2><p>{beat.location}</p><div className="chapter-progress"><span style={{width:`${(game.scene+1)/scenes.length*100}%`}}/></div><small>每一步，都在改写原定命运</small><button className="aside-fate" onClick={() => setModal("fate")}><Icon name="spark"/>查看命运面板 ↗</button><div className="aside-quote">“你不是谁的女配，<br/>你是你自己。”</div></aside><article className="reader-card"><div className="card-top"><span><i/>{beat.location}</span><span>{saveOk ? "✓ 已自动存档" : "本机存档不可用"}</span></div><div className="reader-heading"><span>REWRITE YOUR DESTINY</span><h2>{beat.finale ? ending.name : beat.heading}</h2></div>{game.phase === "intro" && <div className="scene-intro">{beat.intro.map(p=><p key={p}>{p}</p>)}</div>}<div className={`dialogue ${speaker === "命运系统" ? "system-dialogue" : ""}`} key={`${game.scene}-${game.phase}`}><div className="speaker"><span className={speaker === "嘉豪" ? "boy" : ""}>{speaker === "嘉豪" ? "嘉" : speaker === "夏知晴" ? "晴" : speaker === "命运系统" ? "✧" : speaker === "我" || speaker.includes("心声") ? "我" : speaker.slice(-1)}</span><div>{speaker}<small>{speaker.includes("心声") ? "你没有说出口的话" : speaker === "嘉豪" ? "看着不靠谱，却一直站在你这边" : ""}</small></div></div><p style={{fontSize}} aria-live="polite">{text}</p></div>{effect && <div className="effect-row">{Object.entries(effect.effects).map(([stat,delta])=><span key={stat}>{statLabels[stat as Stat]} {delta! > 0 ? "+" : ""}{delta}</span>)}</div>}{bullets && game.phase === "intro" && beat.bullet && <div className="system-block"><Icon name="chat"/><div><small>来自故事之外的弹幕</small><p>{beat.bullet}</p></div></div>}{game.phase === "intro" && beat.choices ? <div className="choices"><div className="choice-label"><span>轮到你做决定了</span><small>选择你想说的话</small></div>{beat.choices.map((c,i)=><button key={c.id} disabled={!ready} onClick={()=>persist(selectChoice(game,c.id))}><span className="choice-index">0{i+1}</span>{c.text}<Icon name="arrow"/></button>)}</div> : beat.finale ? <div className="demo-ending"><div className="ending-tag">{ending.tag}</div><p className="ending-description">{ending.text}</p><div className="system-block"><Icon name="spark"/><div><small>下一段人生</small><p>{ending.after}</p></div></div><div className="ending-summary"><h3>这一路，你做过的决定</h3>{game.flags.map((flag,i)=><p key={flag}><span>{String(i+1).padStart(2,"0")}</span>{flag}</p>)}</div><div className="ending-actions"><button className="primary" onClick={start}>重新开始 <Icon name="arrow"/></button><button className="back-link" onClick={()=>setModal("fate")}>查看最终状态 ↗</button></div></div> : <div className="next-actions"><span>{effect ? "选择已留下回响。" : "点击继续，故事向前。"}</span><button className="primary" disabled={!ready} onClick={()=>persist(advance(game))}>继续剧情 <Icon name="arrow"/></button></div>}</article></>}
    </main><footer className="footer"><span>不做命运的配角。</span><span>阅读 · 选择 · 改写 <i/> 一个关于夺回人生的故事</span><span>扶弟魔模拟器 <b>© 2026</b></span></footer>
    {modal && <div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close" autoFocus onClick={()=>setModal(null)} aria-label="关闭"><Icon name="close"/></button><div className="eyebrow">REWRITE YOUR DESTINY</div><h2 id="modal-title">{modal === "fate" ? "你的命运面板" : "按你的节奏体验"}</h2>{modal === "fate" ? <><p className="modal-description">数字记录你的选择，不定义你是谁。</p><div className="stats">{stats.map(([name,value])=><div key={name}><span>{name}<b>{value}<small> / 100</small></b></span><div><i style={{width:`${value}%`}}/></div></div>)}</div><div className="fate-tag"><span>已解锁结局 · {game.endings.length} / 3</span><p>{game.endings.length ? game.endings.map(id=>({self:"自我剧本",road:"仍在路上",return:"剧本回潮"})[id]).join(" · ") : "等你写下第一个结局"}</p><span>已留下的命运印记</span>{game.flags.length ? game.flags.map(flag=><p key={flag}>{flag}</p>) : <p>故事尚未落笔</p>}</div></> : <div className="setting-list"><div><span>剧情字号<small>黑体，清晰易读</small></span><div className="font-controls"><button aria-label="减小字号" disabled={fontSize<=16} onClick={()=>setFontSize(v=>v-2)}>−</button><b>{fontSize}</b><button aria-label="增大字号" disabled={fontSize>=24} onClick={()=>setFontSize(v=>v+2)}>+</button></div></div><div><span>弹幕提示<small>选择后的数值反馈始终显示</small></span><button className={`toggle ${bullets ? "on" : ""}`} role="switch" aria-label="弹幕开关" aria-checked={bullets} onClick={()=>setBullets(v=>!v)}><i/></button></div><p className="setting-sample" style={{fontSize}}>“我的人生，我自己来写。”</p><button className="back-link" onClick={()=>{setModal(null);requestStart();}}>重新开始 ↗</button></div>}</section></div>}
  {restartOpen && <div className="modal-backdrop" onClick={()=>setRestartOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="restart-title" onClick={e=>e.stopPropagation()}><h2 id="restart-title">重新开始这段人生？</h2><p className="modal-description">当前进度会被新的故事覆盖，已解锁的结局会保留。</p><div className="ending-actions"><button className="primary" onClick={start}>重新开始</button><button className="back-link" autoFocus onClick={()=>setRestartOpen(false)}>保留当前进度</button></div></section></div>}
  </div>;
}
